version: 2
env:
  - CGO_ENABLED=1
builds:
  - id: linux_amd64
    goos:
      - linux
    goarch:
      - amd64
  - id: linux_arm
    goos:
      - linux
    goarch:
      - arm
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
    goarm:
      - "6"
      - "7"
  - id: linux_arm64
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
  - id: windows_amd64
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
  - id: windows_arm64
    goos:
      - windows
    goarch:
      - arm64
    env:
      - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
  - id: darwin_amd64
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
  - id: darwin_arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
archives:
  - formats: ["binary"]
release:
  draft: false
changelog:
  disable: true
