name: release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    container: ghcr.io/goreleaser/goreleaser-cross
    steps:
      - uses: actions/checkout@v4
        with:
          set-safe-directory: true
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod
      - name: "Run goreleaser"
        run: "git config --global --add safe.directory $(pwd) && goreleaser release --clean"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
